---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: read-receipt-db-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  local:
    path: /mnt
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-west-2a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: read-receipt-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 200Mi
